// <auto-generated />
using System;
using ChinaFoodManagementV2.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChinaFoodManagementV2.Migrations
{
    [DbContext(typeof(ChinaFoodDBContext))]
    partial class ChinaFoodDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChinaFoodManagementV2.Entity.Account", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnName("user_name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DisplayName")
                        .HasColumnName("display_name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("LoginError")
                        .HasColumnName("login_error")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnName("user_type")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.HasKey("UserName");

                    b.ToTable("tbl_account");
                });

            modelBuilder.Entity("ChinaFoodManagementV2.Entity.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCheckin")
                        .HasColumnName("date_checkin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCheckout")
                        .HasColumnName("date_checkout")
                        .HasColumnType("DateTime");

                    b.Property<int?>("Discount")
                        .HasColumnName("discount")
                        .HasColumnType("int");

                    b.Property<int>("StatusPaid")
                        .HasColumnName("status_paid")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnName("table_id")
                        .HasColumnType("int");

                    b.Property<long?>("TotalPrice")
                        .HasColumnName("total_price")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("tbl_bill");
                });

            modelBuilder.Entity("ChinaFoodManagementV2.Entity.BillInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BillId")
                        .HasColumnName("bill_id")
                        .HasColumnType("int");

                    b.Property<int>("FoodCount")
                        .HasColumnName("food_count")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnName("food_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("FoodId");

                    b.ToTable("tbl_bill_info");
                });

            modelBuilder.Entity("ChinaFoodManagementV2.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnName("category_name")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("tbl_category");
                });

            modelBuilder.Entity("ChinaFoodManagementV2.Entity.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnName("category_id")
                        .HasColumnType("int");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnName("food_name")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<long>("Price")
                        .HasColumnName("food_price")
                        .HasColumnType("bigint")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("tbl_food");
                });

            modelBuilder.Entity("ChinaFoodManagementV2.Entity.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustName")
                        .IsRequired()
                        .HasColumnName("cust_name")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("PeopleNum")
                        .HasColumnName("people_num")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasColumnType("nvarchar(13)")
                        .HasMaxLength(13);

                    b.Property<DateTime>("ResDate")
                        .HasColumnName("res_date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("ResTime")
                        .HasColumnName("res_time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("tbl_reservation");
                });

            modelBuilder.Entity("ChinaFoodManagementV2.Entity.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnName("table_name")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("TableStatus")
                        .HasColumnName("table_status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_table");
                });

            modelBuilder.Entity("ChinaFoodManagementV2.Entity.Bill", b =>
                {
                    b.HasOne("ChinaFoodManagementV2.Entity.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ChinaFoodManagementV2.Entity.BillInfo", b =>
                {
                    b.HasOne("ChinaFoodManagementV2.Entity.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ChinaFoodManagementV2.Entity.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChinaFoodManagementV2.Entity.Food", b =>
                {
                    b.HasOne("ChinaFoodManagementV2.Entity.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
